function create_Spikes_figure(time, YMatrix1,ttxt)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 03-Apr-2014 21:43:09
% Create multiple lines using matrix input to plot
 clrlst = [{'k'},{'r'},{'b'},{'g'},{'c'},{'m'},{'y'},{'p'},{'k'},{'r'},{'b'},{'g'},{'c'},{'m'},{'y'},{'p'}];

if size(YMatrix1,1)>16
    error('there are more trials than I can handle. should be less then 16, better less than 8')
end

for i = 1: size(YMatrix1,1)
plot(time, YMatrix1(i,:) + 0.2*(i-1),clrlst{i});
hold on
end
hold off


% Create title
title(ttxt);

% Create xlabel
xlabel('time (sec)');
ylim([-.2 1.1])
xlim([0 max(time)])

