function create_Spikes_figure1(time, YMatrix1,ttxt,offset,ylimm)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 03-Apr-2014 21:43:09
% Create multiple lines using matrix input to plot

 clrlst = [{'k'},{'r'},{'b'},{'g'},{'c'},{'m'},{'y'},{'p'},{'k'},{'r'},{'b'},{'g'},{'c'},{'m'},{'y'},{'p'}];

if size(YMatrix1,1)>16
    error('there are more trials than I can handle. should be less then 16, better less than 8')
end

for i = 1: size(YMatrix1,1)
plot(time, YMatrix1(i,:) + offset*(i-1),clrlst{i});
hold on
end
plot(time,mean(YMatrix1,1)+offset*(i),'--r')
hold off

% Create title
title(ttxt);

% Create xlabel
xlabel('time (sec)');
ylim(ylimm)
xlim([0 max(time)])

